server:
  port: 8082

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES}

broker:
  queue:
    processamento:
      name: processamento
  exchange:
    processamento:
      name: processamento